//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsCertcar.ServicoNortix {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://webservices.nortix.com.br/webservices/", ConfigurationName="ServicoNortix.clsLeilao2Soap")]
    public interface clsLeilao2Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.nortix.com.br/webservices/InputVsBol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WsCertcar.ServicoNortix.struct_RespostaBol InputVsBol(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.nortix.com.br/webservices/InputVsBol", ReplyAction="*")]
        System.Threading.Tasks.Task<WsCertcar.ServicoNortix.struct_RespostaBol> InputVsBolAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.nortix.com.br/webservices/InputVsRst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WsCertcar.ServicoNortix.struct_RespostaRst InputVsRst(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.nortix.com.br/webservices/InputVsRst", ReplyAction="*")]
        System.Threading.Tasks.Task<WsCertcar.ServicoNortix.struct_RespostaRst> InputVsRstAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.nortix.com.br/webservices/InputVsDst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WsCertcar.ServicoNortix.struct_RespostaDst InputVsDst(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.nortix.com.br/webservices/InputVsDst", ReplyAction="*")]
        System.Threading.Tasks.Task<WsCertcar.ServicoNortix.struct_RespostaDst> InputVsDstAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.nortix.com.br/webservices/InputVsRstFoto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WsCertcar.ServicoNortix.struct_RespostaRstFoto InputVsRstFoto(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.nortix.com.br/webservices/InputVsRstFoto", ReplyAction="*")]
        System.Threading.Tasks.Task<WsCertcar.ServicoNortix.struct_RespostaRstFoto> InputVsRstFotoAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.nortix.com.br/webservices/InputVsDstFoto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WsCertcar.ServicoNortix.struct_RespostaDst InputVsDstFoto(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.nortix.com.br/webservices/InputVsDstFoto", ReplyAction="*")]
        System.Threading.Tasks.Task<WsCertcar.ServicoNortix.struct_RespostaDst> InputVsDstFotoAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.nortix.com.br/webservices/")]
    public partial class struct_RespostaBol : object, System.ComponentModel.INotifyPropertyChanged {
        
        private struct_Identificacao identificacaoField;
        
        private struct_Controle controleField;
        
        private bool respostaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public struct_Identificacao Identificacao {
            get {
                return this.identificacaoField;
            }
            set {
                this.identificacaoField = value;
                this.RaisePropertyChanged("Identificacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public struct_Controle Controle {
            get {
                return this.controleField;
            }
            set {
                this.controleField = value;
                this.RaisePropertyChanged("Controle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Resposta {
            get {
                return this.respostaField;
            }
            set {
                this.respostaField = value;
                this.RaisePropertyChanged("Resposta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.nortix.com.br/webservices/")]
    public partial class struct_Identificacao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nomeDaTransacaoField;
        
        private string descricaoDaTransacaoField;
        
        private string versaoDaTransacaoField;
        
        private System.DateTime dataDaPublicacaoField;
        
        private string autorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NomeDaTransacao {
            get {
                return this.nomeDaTransacaoField;
            }
            set {
                this.nomeDaTransacaoField = value;
                this.RaisePropertyChanged("NomeDaTransacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DescricaoDaTransacao {
            get {
                return this.descricaoDaTransacaoField;
            }
            set {
                this.descricaoDaTransacaoField = value;
                this.RaisePropertyChanged("DescricaoDaTransacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string VersaoDaTransacao {
            get {
                return this.versaoDaTransacaoField;
            }
            set {
                this.versaoDaTransacaoField = value;
                this.RaisePropertyChanged("VersaoDaTransacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime DataDaPublicacao {
            get {
                return this.dataDaPublicacaoField;
            }
            set {
                this.dataDaPublicacaoField = value;
                this.RaisePropertyChanged("DataDaPublicacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Autor {
            get {
                return this.autorField;
            }
            set {
                this.autorField = value;
                this.RaisePropertyChanged("Autor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.nortix.com.br/webservices/")]
    public partial class struct_LeilaoFoto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long nsuVeiculoField;
        
        private long idLeilaoField;
        
        private string loteField;
        
        private string marcaField;
        
        private string modeloField;
        
        private int anoModeloField;
        
        private int anoFabricacaoField;
        
        private string placaField;
        
        private string chassiField;
        
        private string renavamField;
        
        private string corField;
        
        private string combustivelField;
        
        private string categoriaDoVeiculoField;
        
        private string condicaoGeralDoVeiculoField;
        
        private string situacaoDoChassiField;
        
        private string nrMotorField;
        
        private string nrCambioField;
        
        private string nrCarroceriaField;
        
        private string nrEixoTraseiroField;
        
        private int quantidadeDeEixosField;
        
        private string patioField;
        
        private string leiloeiroField;
        
        private System.DateTime dataLeilaoField;
        
        private string comitenteField;
        
        private int sucateamentoField;
        
        private string nomeFoto1Field;
        
        private string nomeFoto2Field;
        
        private string nomeFoto3Field;
        
        private string nomeFoto4Field;
        
        private string urlFoto1Field;
        
        private string urlFoto2Field;
        
        private string urlFoto3Field;
        
        private string urlFoto4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long NsuVeiculo {
            get {
                return this.nsuVeiculoField;
            }
            set {
                this.nsuVeiculoField = value;
                this.RaisePropertyChanged("NsuVeiculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long IdLeilao {
            get {
                return this.idLeilaoField;
            }
            set {
                this.idLeilaoField = value;
                this.RaisePropertyChanged("IdLeilao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Lote {
            get {
                return this.loteField;
            }
            set {
                this.loteField = value;
                this.RaisePropertyChanged("Lote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("Marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
                this.RaisePropertyChanged("Modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int AnoModelo {
            get {
                return this.anoModeloField;
            }
            set {
                this.anoModeloField = value;
                this.RaisePropertyChanged("AnoModelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int AnoFabricacao {
            get {
                return this.anoFabricacaoField;
            }
            set {
                this.anoFabricacaoField = value;
                this.RaisePropertyChanged("AnoFabricacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
                this.RaisePropertyChanged("Placa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Chassi {
            get {
                return this.chassiField;
            }
            set {
                this.chassiField = value;
                this.RaisePropertyChanged("Chassi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Renavam {
            get {
                return this.renavamField;
            }
            set {
                this.renavamField = value;
                this.RaisePropertyChanged("Renavam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Cor {
            get {
                return this.corField;
            }
            set {
                this.corField = value;
                this.RaisePropertyChanged("Cor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Combustivel {
            get {
                return this.combustivelField;
            }
            set {
                this.combustivelField = value;
                this.RaisePropertyChanged("Combustivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string CategoriaDoVeiculo {
            get {
                return this.categoriaDoVeiculoField;
            }
            set {
                this.categoriaDoVeiculoField = value;
                this.RaisePropertyChanged("CategoriaDoVeiculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string CondicaoGeralDoVeiculo {
            get {
                return this.condicaoGeralDoVeiculoField;
            }
            set {
                this.condicaoGeralDoVeiculoField = value;
                this.RaisePropertyChanged("CondicaoGeralDoVeiculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string SituacaoDoChassi {
            get {
                return this.situacaoDoChassiField;
            }
            set {
                this.situacaoDoChassiField = value;
                this.RaisePropertyChanged("SituacaoDoChassi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string NrMotor {
            get {
                return this.nrMotorField;
            }
            set {
                this.nrMotorField = value;
                this.RaisePropertyChanged("NrMotor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string NrCambio {
            get {
                return this.nrCambioField;
            }
            set {
                this.nrCambioField = value;
                this.RaisePropertyChanged("NrCambio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string NrCarroceria {
            get {
                return this.nrCarroceriaField;
            }
            set {
                this.nrCarroceriaField = value;
                this.RaisePropertyChanged("NrCarroceria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string NrEixoTraseiro {
            get {
                return this.nrEixoTraseiroField;
            }
            set {
                this.nrEixoTraseiroField = value;
                this.RaisePropertyChanged("NrEixoTraseiro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int QuantidadeDeEixos {
            get {
                return this.quantidadeDeEixosField;
            }
            set {
                this.quantidadeDeEixosField = value;
                this.RaisePropertyChanged("QuantidadeDeEixos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Patio {
            get {
                return this.patioField;
            }
            set {
                this.patioField = value;
                this.RaisePropertyChanged("Patio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Leiloeiro {
            get {
                return this.leiloeiroField;
            }
            set {
                this.leiloeiroField = value;
                this.RaisePropertyChanged("Leiloeiro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public System.DateTime DataLeilao {
            get {
                return this.dataLeilaoField;
            }
            set {
                this.dataLeilaoField = value;
                this.RaisePropertyChanged("DataLeilao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Comitente {
            get {
                return this.comitenteField;
            }
            set {
                this.comitenteField = value;
                this.RaisePropertyChanged("Comitente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int Sucateamento {
            get {
                return this.sucateamentoField;
            }
            set {
                this.sucateamentoField = value;
                this.RaisePropertyChanged("Sucateamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string NomeFoto1 {
            get {
                return this.nomeFoto1Field;
            }
            set {
                this.nomeFoto1Field = value;
                this.RaisePropertyChanged("NomeFoto1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string NomeFoto2 {
            get {
                return this.nomeFoto2Field;
            }
            set {
                this.nomeFoto2Field = value;
                this.RaisePropertyChanged("NomeFoto2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string NomeFoto3 {
            get {
                return this.nomeFoto3Field;
            }
            set {
                this.nomeFoto3Field = value;
                this.RaisePropertyChanged("NomeFoto3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string NomeFoto4 {
            get {
                return this.nomeFoto4Field;
            }
            set {
                this.nomeFoto4Field = value;
                this.RaisePropertyChanged("NomeFoto4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string UrlFoto1 {
            get {
                return this.urlFoto1Field;
            }
            set {
                this.urlFoto1Field = value;
                this.RaisePropertyChanged("UrlFoto1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string UrlFoto2 {
            get {
                return this.urlFoto2Field;
            }
            set {
                this.urlFoto2Field = value;
                this.RaisePropertyChanged("UrlFoto2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string UrlFoto3 {
            get {
                return this.urlFoto3Field;
            }
            set {
                this.urlFoto3Field = value;
                this.RaisePropertyChanged("UrlFoto3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string UrlFoto4 {
            get {
                return this.urlFoto4Field;
            }
            set {
                this.urlFoto4Field = value;
                this.RaisePropertyChanged("UrlFoto4");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.nortix.com.br/webservices/")]
    public partial class struct_RespostaRstFoto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private struct_Identificacao identificacaoField;
        
        private struct_Controle controleField;
        
        private struct_LeilaoFoto[] respostaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public struct_Identificacao Identificacao {
            get {
                return this.identificacaoField;
            }
            set {
                this.identificacaoField = value;
                this.RaisePropertyChanged("Identificacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public struct_Controle Controle {
            get {
                return this.controleField;
            }
            set {
                this.controleField = value;
                this.RaisePropertyChanged("Controle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public struct_LeilaoFoto[] Resposta {
            get {
                return this.respostaField;
            }
            set {
                this.respostaField = value;
                this.RaisePropertyChanged("Resposta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.nortix.com.br/webservices/")]
    public partial class struct_Controle : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoDeControleField;
        
        private e_Severidade severidadeField;
        
        private string descricaoField;
        
        private e_Acao acaoAdotadaField;
        
        private e_ResultadoDaPesquisa resultadoDaPesquisaField;
        
        private e_GravacaoDeLog gravacaoDoLogField;
        
        private System.DateTime dataExecucaoField;
        
        private string observacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CodigoDeControle {
            get {
                return this.codigoDeControleField;
            }
            set {
                this.codigoDeControleField = value;
                this.RaisePropertyChanged("CodigoDeControle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public e_Severidade Severidade {
            get {
                return this.severidadeField;
            }
            set {
                this.severidadeField = value;
                this.RaisePropertyChanged("Severidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("Descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public e_Acao AcaoAdotada {
            get {
                return this.acaoAdotadaField;
            }
            set {
                this.acaoAdotadaField = value;
                this.RaisePropertyChanged("AcaoAdotada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public e_ResultadoDaPesquisa ResultadoDaPesquisa {
            get {
                return this.resultadoDaPesquisaField;
            }
            set {
                this.resultadoDaPesquisaField = value;
                this.RaisePropertyChanged("ResultadoDaPesquisa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public e_GravacaoDeLog GravacaoDoLog {
            get {
                return this.gravacaoDoLogField;
            }
            set {
                this.gravacaoDoLogField = value;
                this.RaisePropertyChanged("GravacaoDoLog");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime DataExecucao {
            get {
                return this.dataExecucaoField;
            }
            set {
                this.dataExecucaoField = value;
                this.RaisePropertyChanged("DataExecucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Observacao {
            get {
                return this.observacaoField;
            }
            set {
                this.observacaoField = value;
                this.RaisePropertyChanged("Observacao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.nortix.com.br/webservices/")]
    public enum e_Severidade {
        
        /// <remarks/>
        e0_NumeradorNaoInicializado,
        
        /// <remarks/>
        e1_MensagemDeInformacaoSimples,
        
        /// <remarks/>
        e2_MensagemDeAdvertencia,
        
        /// <remarks/>
        e3_MensagemDeErro,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.nortix.com.br/webservices/")]
    public enum e_Acao {
        
        /// <remarks/>
        e0_NumeradorNaoInicializado,
        
        /// <remarks/>
        e1_TrasacaoFoiExecutada,
        
        /// <remarks/>
        e2_TransacaoNaoFoiExecutada,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.nortix.com.br/webservices/")]
    public enum e_ResultadoDaPesquisa {
        
        /// <remarks/>
        e0_NumeradorNaoInicializado,
        
        /// <remarks/>
        e1_RegistrosForamLocalizados,
        
        /// <remarks/>
        e2_RegistrosNaoForamLocalizados,
        
        /// <remarks/>
        e3_RegistrosNemForamPesquisados,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.nortix.com.br/webservices/")]
    public enum e_GravacaoDeLog {
        
        /// <remarks/>
        e0_NumeradorNaoInicializado,
        
        /// <remarks/>
        e1_TransacaoFoiLogada,
        
        /// <remarks/>
        e2_TransacaoNaoFoiLogada,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.nortix.com.br/webservices/")]
    public partial class struct_RespostaDst : object, System.ComponentModel.INotifyPropertyChanged {
        
        private struct_Identificacao identificacaoField;
        
        private struct_Controle controleField;
        
        private System.Data.DataSet respostaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public struct_Identificacao Identificacao {
            get {
                return this.identificacaoField;
            }
            set {
                this.identificacaoField = value;
                this.RaisePropertyChanged("Identificacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public struct_Controle Controle {
            get {
                return this.controleField;
            }
            set {
                this.controleField = value;
                this.RaisePropertyChanged("Controle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Data.DataSet Resposta {
            get {
                return this.respostaField;
            }
            set {
                this.respostaField = value;
                this.RaisePropertyChanged("Resposta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.nortix.com.br/webservices/")]
    public partial class struct_Leilao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long nsuVeiculoField;
        
        private long idLeilaoField;
        
        private string loteField;
        
        private string marcaField;
        
        private string modeloField;
        
        private int anoModeloField;
        
        private int anoFabricacaoField;
        
        private string placaField;
        
        private string chassiField;
        
        private string renavamField;
        
        private string corField;
        
        private string combustivelField;
        
        private string categoriaDoVeiculoField;
        
        private string condicaoGeralDoVeiculoField;
        
        private string situacaoDoChassiField;
        
        private string nrMotorField;
        
        private string nrCambioField;
        
        private string nrCarroceriaField;
        
        private string nrEixoTraseiroField;
        
        private int quantidadeDeEixosField;
        
        private string patioField;
        
        private string leiloeiroField;
        
        private System.DateTime dataLeilaoField;
        
        private string comitenteField;
        
        private int sucateamentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long NsuVeiculo {
            get {
                return this.nsuVeiculoField;
            }
            set {
                this.nsuVeiculoField = value;
                this.RaisePropertyChanged("NsuVeiculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long IdLeilao {
            get {
                return this.idLeilaoField;
            }
            set {
                this.idLeilaoField = value;
                this.RaisePropertyChanged("IdLeilao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Lote {
            get {
                return this.loteField;
            }
            set {
                this.loteField = value;
                this.RaisePropertyChanged("Lote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("Marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
                this.RaisePropertyChanged("Modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int AnoModelo {
            get {
                return this.anoModeloField;
            }
            set {
                this.anoModeloField = value;
                this.RaisePropertyChanged("AnoModelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int AnoFabricacao {
            get {
                return this.anoFabricacaoField;
            }
            set {
                this.anoFabricacaoField = value;
                this.RaisePropertyChanged("AnoFabricacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
                this.RaisePropertyChanged("Placa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Chassi {
            get {
                return this.chassiField;
            }
            set {
                this.chassiField = value;
                this.RaisePropertyChanged("Chassi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Renavam {
            get {
                return this.renavamField;
            }
            set {
                this.renavamField = value;
                this.RaisePropertyChanged("Renavam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Cor {
            get {
                return this.corField;
            }
            set {
                this.corField = value;
                this.RaisePropertyChanged("Cor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Combustivel {
            get {
                return this.combustivelField;
            }
            set {
                this.combustivelField = value;
                this.RaisePropertyChanged("Combustivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string CategoriaDoVeiculo {
            get {
                return this.categoriaDoVeiculoField;
            }
            set {
                this.categoriaDoVeiculoField = value;
                this.RaisePropertyChanged("CategoriaDoVeiculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string CondicaoGeralDoVeiculo {
            get {
                return this.condicaoGeralDoVeiculoField;
            }
            set {
                this.condicaoGeralDoVeiculoField = value;
                this.RaisePropertyChanged("CondicaoGeralDoVeiculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string SituacaoDoChassi {
            get {
                return this.situacaoDoChassiField;
            }
            set {
                this.situacaoDoChassiField = value;
                this.RaisePropertyChanged("SituacaoDoChassi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string NrMotor {
            get {
                return this.nrMotorField;
            }
            set {
                this.nrMotorField = value;
                this.RaisePropertyChanged("NrMotor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string NrCambio {
            get {
                return this.nrCambioField;
            }
            set {
                this.nrCambioField = value;
                this.RaisePropertyChanged("NrCambio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string NrCarroceria {
            get {
                return this.nrCarroceriaField;
            }
            set {
                this.nrCarroceriaField = value;
                this.RaisePropertyChanged("NrCarroceria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string NrEixoTraseiro {
            get {
                return this.nrEixoTraseiroField;
            }
            set {
                this.nrEixoTraseiroField = value;
                this.RaisePropertyChanged("NrEixoTraseiro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int QuantidadeDeEixos {
            get {
                return this.quantidadeDeEixosField;
            }
            set {
                this.quantidadeDeEixosField = value;
                this.RaisePropertyChanged("QuantidadeDeEixos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Patio {
            get {
                return this.patioField;
            }
            set {
                this.patioField = value;
                this.RaisePropertyChanged("Patio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Leiloeiro {
            get {
                return this.leiloeiroField;
            }
            set {
                this.leiloeiroField = value;
                this.RaisePropertyChanged("Leiloeiro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public System.DateTime DataLeilao {
            get {
                return this.dataLeilaoField;
            }
            set {
                this.dataLeilaoField = value;
                this.RaisePropertyChanged("DataLeilao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Comitente {
            get {
                return this.comitenteField;
            }
            set {
                this.comitenteField = value;
                this.RaisePropertyChanged("Comitente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int Sucateamento {
            get {
                return this.sucateamentoField;
            }
            set {
                this.sucateamentoField = value;
                this.RaisePropertyChanged("Sucateamento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservices.nortix.com.br/webservices/")]
    public partial class struct_RespostaRst : object, System.ComponentModel.INotifyPropertyChanged {
        
        private struct_Identificacao identificacaoField;
        
        private struct_Controle controleField;
        
        private struct_Leilao[] respostaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public struct_Identificacao Identificacao {
            get {
                return this.identificacaoField;
            }
            set {
                this.identificacaoField = value;
                this.RaisePropertyChanged("Identificacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public struct_Controle Controle {
            get {
                return this.controleField;
            }
            set {
                this.controleField = value;
                this.RaisePropertyChanged("Controle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public struct_Leilao[] Resposta {
            get {
                return this.respostaField;
            }
            set {
                this.respostaField = value;
                this.RaisePropertyChanged("Resposta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface clsLeilao2SoapChannel : WsCertcar.ServicoNortix.clsLeilao2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class clsLeilao2SoapClient : System.ServiceModel.ClientBase<WsCertcar.ServicoNortix.clsLeilao2Soap>, WsCertcar.ServicoNortix.clsLeilao2Soap {
        
        public clsLeilao2SoapClient() {
        }
        
        public clsLeilao2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public clsLeilao2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public clsLeilao2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public clsLeilao2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WsCertcar.ServicoNortix.struct_RespostaBol InputVsBol(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi) {
            return base.Channel.InputVsBol(pstrCliente, pstrLogin, pstrSenha, pstrPlaca, pstrChassi);
        }
        
        public System.Threading.Tasks.Task<WsCertcar.ServicoNortix.struct_RespostaBol> InputVsBolAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi) {
            return base.Channel.InputVsBolAsync(pstrCliente, pstrLogin, pstrSenha, pstrPlaca, pstrChassi);
        }
        
        public WsCertcar.ServicoNortix.struct_RespostaRst InputVsRst(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi) {
            return base.Channel.InputVsRst(pstrCliente, pstrLogin, pstrSenha, pstrPlaca, pstrChassi);
        }
        
        public System.Threading.Tasks.Task<WsCertcar.ServicoNortix.struct_RespostaRst> InputVsRstAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi) {
            return base.Channel.InputVsRstAsync(pstrCliente, pstrLogin, pstrSenha, pstrPlaca, pstrChassi);
        }
        
        public WsCertcar.ServicoNortix.struct_RespostaDst InputVsDst(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi) {
            return base.Channel.InputVsDst(pstrCliente, pstrLogin, pstrSenha, pstrPlaca, pstrChassi);
        }
        
        public System.Threading.Tasks.Task<WsCertcar.ServicoNortix.struct_RespostaDst> InputVsDstAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi) {
            return base.Channel.InputVsDstAsync(pstrCliente, pstrLogin, pstrSenha, pstrPlaca, pstrChassi);
        }
        
        public WsCertcar.ServicoNortix.struct_RespostaRstFoto InputVsRstFoto(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi) {
            return base.Channel.InputVsRstFoto(pstrCliente, pstrLogin, pstrSenha, pstrPlaca, pstrChassi);
        }
        
        public System.Threading.Tasks.Task<WsCertcar.ServicoNortix.struct_RespostaRstFoto> InputVsRstFotoAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi) {
            return base.Channel.InputVsRstFotoAsync(pstrCliente, pstrLogin, pstrSenha, pstrPlaca, pstrChassi);
        }
        
        public WsCertcar.ServicoNortix.struct_RespostaDst InputVsDstFoto(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi) {
            return base.Channel.InputVsDstFoto(pstrCliente, pstrLogin, pstrSenha, pstrPlaca, pstrChassi);
        }
        
        public System.Threading.Tasks.Task<WsCertcar.ServicoNortix.struct_RespostaDst> InputVsDstFotoAsync(string pstrCliente, string pstrLogin, string pstrSenha, string pstrPlaca, string pstrChassi) {
            return base.Channel.InputVsDstFotoAsync(pstrCliente, pstrLogin, pstrSenha, pstrPlaca, pstrChassi);
        }
    }
}
